# modified: 2026-10-05 by Max Dernovyi: curl extension and lint step
name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: soap, simplexml, openssl, curl
          coverage: none

      - name: Lint
        run: docker/lint.sh src/Rest src/NetSuiteClient.php tests

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit

      - name: Run PHPSpec
        run: vendor/bin/phpspec run
